### ISSUE TITLE
Spindly Gem Crabs Die when Out of Water

### ISSUE THREAD

**Issue by BobbyLinMC** [teamdraco/finsandtails#4]
Hello. First of I like to say that this mod is fantastic and is one of my top 5 best/favorite mods. One problem I have is with the Spindly Gem Crabs. So basically, I'm building a swamp pond in my village and the Spindly Gem Crab is a great addition to the pond. But they usually would come up to land or out of water and soon die.  That causes me to keep spawning them over and over again. So can you fix this problem in the future updates? I also want more color variations of the Spindly Gem Crab, for example; teal, amethyst, lime, and such. Thank you!! Love this mod!!

**Comment by Coda1552** [comment]
Hello, I'm glad you like the mod! We've worked very hard on it. Unfortunately I am unable to figure out how to make the crabs stay in the water. It happens with flatback suckers, too. I'll continue to try and figure it out. I'd recommend building higher walls so they can't get out of the water.

**Comment by Coda1552** [comment]
Forgot to close this, but it should be fixed in 2.0.0, whenever thats released.
